In [1]:
# TO DO
# Check why max_id doesnt work

# Check if names have multiple entries
# Retrieve all keys in dictionary that do not contain

In [41]:
# Workable API
import requests
import pandas as pd
import datetime
from datetime import date


headers={'Authorization': 'Bearer 229aa3876e4fc4447460a13da7f57d1be4111202e1d56d4d0231fb932c1e7cd1'}
url = 'https://jdriven.workable.com/spi/v3/'

#r_jobs = requests.get(url+'jobs.json', headers=headers)
#r_stages = requests.get(url+'stages.json', headers=headers)
#r_cand = requests.get(url+'candidates.json', headers=headers)

#By default results are limited to 50. The limit can by updated via the request parameter limit
#The value specified cannot be more than 100.
#cand_dict['paging']
#{'next': 'https://jdriven.workable.com/spi/v3/candidates?limit=50&since_id=e48b5d'}

#since_id: string. Returns results with an ID greater than or equal to the specified ID

#paging indicates what the next webpage is. 
# Since_id indicates that the requested data is taken before the since_ID
# In other words, the next page starts with since_D
# {'next': 'https://jdriven.workable.com/spi/v3/candidates?limit=100&since_id=f36d27'}
# Limit indicates the number of IDs retrieved before the since_ID

#max_id
# Get max_id, limit=100 to get the 100 latest entries
# Then use the first entry of that request for the following request, using since_Id=first entry of the first request

# I want to retrieve the last ID
# Maybe can retrieve using created_after and setting this to last week. If it cannot find anything, using another week back in time
#'https://jdriven.workable.com/spi/v3/candidates?limit=100&created_after=2019-09-01T13:29:49Z}'


#Timestamp parameters input format
#Supported input formats for the timestamp fields created_after & updated_after are:
#ISO8601 e.g. 20150708T115616Z
#Unix time (e.g. 1436356721)

In [42]:
from collections import Sequence
from itertools import chain, count, tee

def locate_element(data,look_up_elem):
    '''
    Function to locate the exact location of a an element in a data structure
    '''
    data_orig = data
    loc_list = []
    
    #### Step 1: Create loop: while look_up_elem not in loc_list
    while look_up_elem not in loc_list:

        data = data_orig
        if loc_list != []:
            for location in loc_list:
                data = data[location]     
        
        #### Step 2: Create loop for each element in data. This element needs to be appended to loc_list if element is found in (sub-levels of) this element
        # Combine step 4 and 5 in one function. Function is to flatten the data and check if look_up_elem is present in data. If element is found, return loc_list
        def check_branche(data):
                    #### Step 2: Check if look_up_element is present on 1st level of data
            if look_up_elem in data:
                loc_list.append(look_up_elem)
                return loc_list

            #### Step 3: If element not present on 1st level, filter out strings and integers from data. Method is different for different data types
            # Note: data_tuple = () (will be problematic, as you cannot append elements to a tuple). We may be able to add items from tuple to list as tuple is also a Sequence

            # Define data_elements
            if type(data)==dict: 
                data_elements = list(data.keys())
            elif type(data)==list: 
                data_elements = list(range(len(data)))
            # elif type(data)==tuple: 
                #data_elements = list(range(len(data)))

            else:
                return "Element not present"
                      
            for element in data_elements:

                data_to_check = data[element]

                # Define data_dict, data_list and data_tuple
                if type(data_to_check)==dict:
                    data_dict = data_to_check
                    data_list = []
                    data_tuple = ()
                elif type(data_to_check)==list:
                    data_dict = {}
                    data_list = data_to_check
                    data_tuple = ()
                elif type(data_to_check)==tuple:
                    data_dict = {}
                    data_list = []
                    data_tuple = data_to_check
                elif type(data_to_check)!=dict and type(data_to_check)!=list and type(data_to_check)!=tuple:
                    continue
                else:
                    return "Error"

                #### Step 5: Enter while loop (is within the for loop of step 4). From the filtered data obtained in step 3, divide the different elements into its data type. Then, flatten type(data) data type first and then the other two data types
                # When look_up_elem is found, append element to loc_list and return loc_list
                while data_dict != {} or data_list != [] or data_tuple !=():
                    # Flatten dictionary and check if element is present on any of the levels and add list elements to data_list
                    # After first round, if any elements were added to data_dict, go through these added elements
                    while data_dict != {}:
                        if look_up_elem in data_dict:
                            loc_list.append(element)
                            return 
                            
                        data_dict_temp = {}
                        # Filter the elements in data_dict
                        for key,value in iter(data_dict.items()):
                            if type(value)==dict:
                                data_dict_temp.update(value)
                            elif type(value)==list:
                                data_list.append(value)
                            #elif type(value)==tuple:
                            #    test_tuple
                            # to check if tuple is also a sequence, can also use chain(element) for this
                            else:
                                "Element is string or integer"
                        data_dict = data_dict_temp

                    # After data_dict is (temporarily) exhausted, go through data_list
                    while data_list != []:
                        if look_up_elem in data_list:
                            loc_list.append(element)
                            return loc_list

                        data_list_temp = []
                        # Filter the elements in data_dict
                        for item in data_list:
                            if type(item)==dict:
                                data_dict.update(item)
                            elif type(item)==list:
                                for i in item:
                                    data_list_temp.append(i)
                            else:
                                "Element is string or integer"
                        data_list = data_list_temp

                    # After data_list is (temporarily) exhausted, go through data_tuple
                    #while data_tuple !=():
                        # Flatten tuple, check if element is present on any of the levels and add dictionary and list elements to data_dict or data_list
                        #pass

            if look_up_elem not in loc_list:
                return "Element not Found"
        check_branche(data)
    
    return loc_list

In [43]:
import copy
def change_name_duplicate_keys(d):
    d_no_dupes = copy.deepcopy(d)
    all_keys = {}
    all_keys_temp = {}
    list_check = []
    duplicate_remover_dict = d_no_dupes  
    while duplicate_remover_dict !={}:
        dict_temp = {}
        no_dupes = 0
        for key,value in iter(duplicate_remover_dict.items()):
            if type(value)==dict and value !={}:
                for k,v in value.items():
                    if k in dict_temp or k in all_keys: 
                        key_to_replace = k
                        key_loc = locate_element(duplicate_remover_dict,key_to_replace)
                        key_new = key_to_replace+'_'+str(key_loc[len(key_loc)-2])
                        replacement_dict = duplicate_remover_dict
                        for key in key_loc[:len(key_loc)-1]:
                            replacement_dict = replacement_dict[key]
                        replacement_dict[key_new] = replacement_dict.pop(key_to_replace)
                        no_dupes = 1
                    else:
                        all_keys_temp.update({k:v})
                if no_dupes ==1:
                    all_keys_temp = {}
                    break
                else:
                    dict_temp.update(value)
            
            elif type(value)==list and value != []:
                if all(type(item) == dict for item in value):
                    for item in value:
                        for k,v in item.items():
                            if k in all_keys or k in dict_temp:
                                key_to_replace = k
                                key_loc = locate_element(duplicate_remover_dict,key_to_replace)
                                key_new = key_to_replace+'_'+str(key_loc[len(key_loc)-2])
                                replacement_dict = duplicate_remover_dict
                                for key in key_loc[:len(key_loc)-1]:
                                    replacement_dict = replacement_dict[key]
                                replacement_dict[key_new] = replacement_dict.pop(key_to_replace)
                                no_dupes = 1
                            else:
                                all_keys_temp.update({k:v})
                        if no_dupes ==1:
                            all_keys_temp = {}
                            break
                        else:
                            dict_temp.update(item)
                else:
                    all_keys_temp.update({key:value})
                    for i in value:
                        list_check.append(i)
                    # Append any dict in value (list) to dict_temp.update 
                    while list_check != []:
                        list_temp = []
                        for item in list_check:
                            if type(item)==dict:
                                # Check if item not duplicate 
                                for k,v in item.items():
                                    if k in all_keys or k in dict_temp:
                                        key_to_replace = k
                                        key_loc = locate_element(duplicate_remover_dict,key_to_replace)
                                        key_new = key_to_replace+'_'+str(key_loc[len(key_loc)-2])
                                        replacement_dict = duplicate_remover_dict
                                        for key in key_loc[:len(key_loc)-1]:
                                            replacement_dict = replacement_dict[key]
                                        replacement_dict[key_new] = replacement_dict.pop(key_to_replace)
                                        no_dupes = 1
                                    else:
                                        all_keys_temp.update({k:v})
                                if no_dupes == 1:
                                    all_keys_temp = {}
                                    break
                                else:
                                    dict_temp.update(item)
                            elif type(item)==list:
                                for i in item:
                                    list_temp.append(i)
                            else:
                                continue
                        list_check = list_temp
                              
            else:
                if key in all_keys or key in dict_temp: 
                    key_to_replace = key
                    key_loc = locate_element(d_no_dupes,key_to_replace) #You use d_no_dupes because duplicate_remover dict has moved 1 level down i.e. key will not be in there anymore
                    type_to_check = d_no_dupes
                    for key in key_loc[:len(key_loc)-1]:
                        type_to_check = type_to_check[key]
                    if len(key_loc) == 1 or type(type_to_check) !=dict:
                        key_new = key_to_replace+'_'+str(key_loc[len(key_loc)-2])
                        replacement_dict = d_no_dupes
                        #You use d_no_dupes because duplicate_remover dict has moved 1 level down i.e. key will not be in there anymore
                        if len(key_loc)>1:
                            for key in key_loc[:len(key_loc)-1]:
                                replacement_dict = replacement_dict[key]
                        replacement_dict[key_new] = replacement_dict.pop(key_to_replace)
                        duplicate_remover_dict.pop(key)
                        no_dupes = 1
                        all_keys_temp = {}
                        break
                else:
                    all_keys_temp.update({key:value})
        if no_dupes ==0:
            duplicate_remover_dict = dict_temp
            all_keys.update(all_keys_temp)
    return d_no_dupes

In [4]:
# Create data dictionary
key_list = [
    'id',
    'name',
    'firstname',
    'lastname',
    'headline',
    'subdomain', 
#    'name', need to rename using retrieve key function
    'shortcode',
    'title',
    'stage',
    'disqualified',
    'disqualification_reason',
    'hired_at',
    'sourced',
    'profile_url',
    'address',
    'phone',
    'email',
    'domain',
    'created_at',
    'updated_at',
]
# Create DataFrame column labels
df_dict = {}
for key in key_list:
    df_dict[key]=[]

In [5]:
# Get latest entry:

section = 'candidates?'
limit='100'

d = datetime.datetime.today().isoformat()
r_last_cand = r = requests.get(url+section+'limit='+limit+'&created_after='+d+'.json', headers=headers)
while len(r_last_cand.json()['candidates'])==0:
    d = (datetime.datetime.today() - datetime.timedelta(days=1)).isoformat()
    r_last_cand = requests.get('https://jdriven.workable.com/spi/v3/candidates?limit=100&created_after='+d+'.json', headers=headers)
last_id = r_last_cand.json()['candidates'][-1]['id']

In [6]:
# Build initial database

# Get first page
cand_id_list = []
workable_start_date = '2010-01-01T10:10:10Z'
r_cand = requests.get(url+'candidates?limit='+limit+'&created_after='+workable_start_date+'.json', headers=headers)
for cand in r_cand.json()['candidates']:
    cand_id_list.append(cand['id'])
    for k in key_list:
        loc = locate_element(cand,k)
        v = cand
        for i in loc:
            v = v[i]
        df_dict[k].append(v)
since_id=r_cand.json()['paging']['next'].split("since_id=",1)[1]

# Get next pages
try:
    while last_id not in cand_id_list:
        r_cand = requests.get('https://jdriven.workable.com/spi/v3/candidates?limit=100&since_id='+since_id+'.json', headers=headers)
        for cand in r_cand.json()['candidates']:
            cand_id_list.append(cand['id'])
            for k in key_list:
                loc = locate_element(cand,k)
                v = cand
                for i in loc:
                    v = v[i]
                df_dict[k].append(v)
        since_id=r_cand.json()['paging']['next'].split("since_id=",1)[1]
except KeyError:
    print('Last candidate entry retrieved')
    last_id = cand_id_list[-1]
    last_id

Last candidate entry retrieved

In [7]:
def update_cand_db(last_id, cand_id_list):
    '''
    Update candidate database with any new candidates added after last candidate entry in DB
    Key Arguments:
    last_id -- id of last entry of the candidate database
    '''
    #Retrieve latest candidates
    r_cand_upd = requests.get(url+'candidates?limit='+limit+'&since_id='+last_id+'.json', headers=headers)
    if len(r_cand_upd.json()['candidates'])>1: # first item in the candidates list is already in the DB
        for new_cand in r_cand_upd.json()['candidates'][1:]:
            cand_id_list.append(new_cand['id'])
        last_id=new_cand['id']
        return cand_id_list
    else:
        print('Nothing to add')
        print(cand_id_list[-1])

In [8]:
update_cand_db(last_id, cand_id_list)

Nothing to add
4743315

In [9]:
cand_id_list[-1]

'4743315'

In [10]:
# Create DataFrame
df = pd.DataFrame.from_dict(df_dict, orient='columns')

In [11]:
df.head()

,id,name,firstname,lastname,headline,subdomain,shortcode,title,stage,disqualified,disqualification_reason,hired_at,sourced,profile_url,address,phone,email,domain,created_at,updated_at
0,ddb204,Niels Drost,Niels,Drost,None,jdriven,A8C5321F60,Big Data Scientist (BDR),1st Interview,True,None,None,True,https://jdriven.workable.com/backend/jobs/3292...,None,+31 6 1543 4021,niels.drost@gmail.com,None,2016-09-05T10:05:28Z,2019-02-01T14:56:34Z
1,ddb571,Paula L Amaral Santos,Paula L,Amaral Santos,None,jdriven,A8C5321F60,Big Data Scientist (BDR),Hired,False,None,2016-10-14T10:04:42Z,True,https://jdriven.workable.com/backend/jobs/3292...,None,None,paula.amrl@gmail.com,None,2016-09-05T10:51:00Z,2019-01-08T12:17:22Z
2,ddb572,Gulliver de Boer,Gulliver,de Boer,None,jdriven,A8C5321F60,Big Data Scientist (BDR),2nd Interview,True,None,None,True,https://jdriven.workable.com/backend/jobs/3292...,None,+31612085780,gulif87@hotmail.com,None,2016-09-05T10:51:04Z,2019-01-28T10:34:24Z
3,ddb582,Pieter Kouyzer,Pieter,Kouyzer,None,jdriven,A8C5321F60,Big Data Scientist (BDR),Talentpool,False,None,None,True,https://jdriven.workable.com/backend/jobs/3292...,None,+31(0)85 0020019,joris.braspenning@careerresult.nl,None,2016-09-05T10:52:07Z,2019-02-01T14:52:58Z
4,ddb9ca,Profiel Van Aris Koning,Profiel Van Aris,Koning,None,jdriven,A8C5321F60,Big Data Scientist (BDR),2nd Interview,True,None,None,True,https://jdriven.workable.com/backend/jobs/3292...,None,None,frank.kurstjens@jdriven.com,None,2016-09-05T11:49:31Z,2019-01-10T14:29:23Z

In [13]:
df[df['name']=='Paula L Amaral Santos']

,id,name,firstname,lastname,headline,subdomain,shortcode,title,stage,disqualified,disqualification_reason,hired_at,sourced,profile_url,address,phone,email,domain,created_at,updated_at
1,ddb571,Paula L Amaral Santos,Paula L,Amaral Santos,None,jdriven,A8C5321F60,Big Data Scientist (BDR),Hired,False,None,2016-10-14T10:04:42Z,True,https://jdriven.workable.com/backend/jobs/3292...,None,None,paula.amrl@gmail.com,None,2016-09-05T10:51:00Z,2019-01-08T12:17:22Z

In [19]:
df[df['firstname']=='Tim']

,id,name,firstname,lastname,headline,subdomain,shortcode,title,stage,disqualified,disqualification_reason,hired_at,sourced,profile_url,address,phone,email,domain,created_at,updated_at
98,eb4afd,Tim van Elteren,Tim,van Elteren,None,jdriven,F2E5FDE7A5,Big Data Engineer (BDR),1st Interview,True,None,None,True,https://jdriven.workable.com/backend/jobs/3316...,None,None,ovidiu.terinte@astburymarsden.com,None,2016-10-03T16:37:39Z,2017-08-28T11:12:38Z
325,1069652,Tim te Beek,Tim,te Beek,None,jdriven,9882E4C0EA,Java Developer (JDriven),Hired,False,None,2017-08-29T18:25:46Z,True,https://jdriven.workable.com/backend/jobs/3315...,None,06-48239160,timtebeek@gmail.com,None,2016-11-28T14:08:42Z,2017-08-29T18:25:46Z
359,10b5b70,Tim Selier,Tim,Selier,Data Scientist at Xomnia B.V.,jdriven,A8C5321F60,Big Data Scientist (BDR),Applied,False,None,None,True,https://jdriven.workable.com/backend/jobs/3292...,"Amsterdam Area, Netherlands",None,None,None,2016-12-07T09:42:53Z,2017-01-12T08:41:45Z
428,1109af0,Tim Claessens,Tim,Claessens,Business Analytics Consultant bij QNH Consulting,jdriven,A8C5321F60,Big Data Scientist (BDR),Applied,False,None,None,True,https://jdriven.workable.com/backend/jobs/3292...,"Utrecht, Netherlands",None,None,search,2016-12-19T09:06:41Z,2018-05-03T12:49:51Z
584,121a807,Tim Sijstermans,Tim,Sijstermans,None,jdriven,46F9A9BEBD,Jr. Java Developer (JCore),Applied,False,None,None,True,https://jdriven.workable.com/backend/jobs/3315...,None,None,None,None,2017-01-22T14:02:29Z,2017-07-06T11:18:07Z
604,122d9d8,Tim de Vries,Tim,de Vries,None,jdriven,8176464B66,Front-End Developer (Divotion),Applied,False,None,None,True,https://jdriven.workable.com/backend/jobs/3403...,None,None,None,None,2017-01-24T10:53:02Z,2019-02-04T12:48:48Z
616,1233ef7,Tim Janssen,Tim,Janssen,None,jdriven,A8C5321F60,Big Data Scientist (BDR),Talentpool,False,None,None,True,https://jdriven.workable.com/backend/jobs/3292...,None,None,None,None,2017-01-24T21:05:10Z,2018-03-08T14:53:10Z
655,1274fbf,Tim van Soest,Tim,van Soest,Lead Architect Big Data Analytics at CGI,jdriven,5FC969C8EC,Big Data Strategist,Review,True,None,None,True,https://jdriven.workable.com/backend/jobs/3983...,"Amsterdam Area, Netherlands",None,None,None,2017-01-31T10:06:37Z,2017-02-21T16:52:28Z
723,12b7a9e,Tim van Cann,Tim,van Cann,Business Analytics consultant @ QNH,jdriven,A8C5321F60,Big Data Scientist (BDR),Talentpool,False,None,None,True,https://jdriven.workable.com/backend/jobs/3292...,None,0643221539,timvancann@gmail.com,None,2017-02-06T15:17:45Z,2019-06-10T20:40:58Z
765,12e48b2,Tim Faase,Tim,Faase,None,jdriven,9882E4C0EA,Java Developer (JDriven),Review,True,None,None,True,https://jdriven.workable.com/backend/jobs/3315...,None,None,None,None,2017-02-09T19:54:33Z,2017-02-13T11:32:48Z
856,1315f57,Tim Stokman,Tim,Stokman,None,jdriven,F2E5FDE7A5,Big Data Engineer (BDR),Review,True,None,None,True,https://jdriven.workable.com/backend/jobs/3316...,None,None,None,None,2017-02-14T16:30:26Z,2017-03-06T15:08:25Z
857,1320082,Tim Soethout,Tim,Soethout,Ing Top Engineer at Ing,jdriven,F2E5FDE7A5,Big Data Engineer (BDR),Applied,False,None,None,True,https://jdriven.workable.com/backend/jobs/3316...,"Amsterdam, Netherlands",None,tim.soethout@phil.uu.nl,None,2017-02-15T13:29:04Z,2017-05-03T14:18:15Z
1076,143f3e3,Tim Zwart,Tim,Zwart,None,jdriven,46F9A9BEBD,Jr. Java Developer (JCore),Talentpool,True,None,None,True,https://jdriven.workable.com/backend/jobs/3315...,None,1487253,None,None,2017-03-16T12:48:31Z,2019-01-09T10:01:57Z
1096,14b018d,Tim Bezemer,Tim,Bezemer,None,jdriven,A8C5321F60,Big Data Scientist (BDR),Shortlisted,False,None,None,True,https://jdriven.workable.com/backend/jobs/3292...,None,+31612773689,bezemer.tim@gmail.com,None,2017-03-27T14:17:36Z,2019-05-16T09:35:52Z
1843,1945e37,Tim Lokers,Tim,Lokers,None,jdriven,46F9A9BEBD,Jr. Java Developer (JCore),Sourced,True,None,None,True,https://jdriven.workable.com/backend/jobs/3315...,None,31648356554,timlokers@live.nl,None,2017-07-20T16:10:37Z,2018-02-20T18:23:10Z
2107,1945f7a,Tim Vos,Tim,Vos,None,jdriven,46F9A9BEBD,Jr. Java Developer (JCore),Sourced,True,None,None,True,https://jdriven.workable.com/backend/jobs/3315...,None,31652296053,snel_vosje@hotmail.com,None,2017-07-20T16:12:09Z,2017-10-04T08:17:53Z
2134,1945f9f,Tim Haberham,Tim,Haberham,None,jdriven,46F9A9BEBD,Jr. Java Developer (JCore),Sourced,True,None,None,True,https://jdriven.workable.com/backend/jobs/3315...,None,31646528158,t-haberham+carrierebeurs@outlook.com,None,2017-07-20T16:12:20Z,2018-02-20T18:42:44Z
2148,1945fb6,Tim Steenvoorden,Tim,Steenvoorden,None,jdriven,46F9A9BEBD,Jr. Java Developer (JCore),Sourced,True,None,None,True,https://jdriven.workable.com/backend/jobs/3315...,None,31641113471,tim.steenvoorden@gmail.com,None,2017-07-20T16:12:27Z,2017-10-03T14:19:54Z
2154,1945fbc,Tim Klaase,Tim,Klaase,None,jdriven,46F9A9BEBD,Jr. Java Developer (JCore),Sourced,True,None,None,True,https://jdriven.workable.com/backend/jobs/3315...,None,31123456789,tim_klaase2@hotmail.com,None,2017-07-20T16:12:29Z,2017-10-03T14:00:28Z
2236,1946028,Tim Boeve,Tim,Boeve,None,jdriven,46F9A9BEBD,Jr. Java Developer (JCore),Sourced,False,None,None,True,https://jdriven.workable.com/backend/jobs/3315...,None,31387507341,tim_boeve@hotmail.com,None,2017-07-20T16:13:04Z,2018-05-22T07:41:56Z
2400,194610a,Tim Nijhof,Tim,Nijhof,None,jdriven,46F9A9BEBD,Jr. Java Developer (JCore),Sourced,False,None,None,True,https://jdriven.workable.com/backend/jobs/3315...,None,31611182888,tim.nijhof@hotmail.com,None,2017-07-20T16:14:13Z,2018-05-23T07:42:55Z
2408,1946117,Tim Pas,Tim,Pas,None,jdriven,46F9A9BEBD,Jr. Java Developer (JCore),Sourced,True,None,None,True,https://jdriven.workable.com/backend/jobs/3315...,None,None,t.pas@student.fontys.nl,None,2017-07-20T16:14:17Z,2017-09-19T13:21:14Z
2484,194617e,Tim Dubbelaar,Tim,Dubbelaar,None,jdriven,46F9A9BEBD,Jr. Java Developer (JCore),Sourced,False,None,None,True,https://jdriven.workable.com/backend/jobs/3315...,None,31631050624,timothy_dub@hotmail.com,None,2017-07-20T16:14:51Z,2018-05-23T07:42:56Z
2641,19ccf2a,Tim Nooren,Tim,Nooren,None,jdriven,F2E5FDE7A5,Big Data Engineer (BDR),Applied,False,None,None,True,https://jdriven.workable.com/backend/jobs/3316...,None,None,None,None,2017-08-02T16:12:56Z,2017-09-14T13:53:57Z
2958,1ca6b8c,Tim Samshuijzen,Tim,Samshuijzen,None,jdriven,9882E4C0EA,Java Developer (JDriven),Review,True,None,None,True,https://jdriven.workable.com/backend/jobs/3315...,None,None,timsamshuijzen@gmail.com,None,2017-10-06T12:46:30Z,2017-12-07T12:37:54Z
3019,1e2f241,Tim Oostelbos,Tim,Oostelbos,None,jdriven,46F9A9BEBD,Jr. Java Developer (JCore),Review,True,None,None,True,https://jdriven.workable.com/backend/jobs/3315...,None,+31 6 122 33 4 73,timoostelbos@hotmail.com,None,2017-11-06T08:53:50Z,2017-11-06T15:59:09Z
3150,2250ec1,Tim Kersten,Tim,Kersten,None,jdriven,A8C5321F60,Big Data Scientist (BDR),Review,True,None,None,True,https://jdriven.workable.com/backend/jobs/3292...,None,None,tajwkersten@gmail.com,None,2018-02-01T14:50:41Z,2019-01-08T12:16:57Z
3334,25d0357,Tim Smeets,Tim,Smeets,None,jdriven,46F9A9BEBD,Jr. Java Developer (JCore),Applied,False,None,None,True,https://jdriven.workable.com/backend/jobs/3315...,None,None,None,None,2018-04-10T09:05:41Z,2018-06-30T07:43:44Z
3429,2970803,Tim Elfrink,Tim,Elfrink,None,jdriven,5E4DC1408A,Data Scientist (Vantage AI),Hired,False,None,2018-08-02T14:00:25Z,True,https://jdriven.workable.com/backend/jobs/6865...,None,06-3400 2547,tim.elfrink.94@gmail.com,None,2018-02-14T16:29:25Z,2019-01-08T12:16:52Z
3616,2ad4767,Tim Mutsaers,Tim,Mutsaers,None,jdriven,46F9A9BEBD,Jr. Java Developer (JCore),Sourced,False,None,None,True,https://jdriven.workable.com/backend/jobs/3315...,None,None,None,None,2018-07-10T09:46:20Z,2018-07-10T09:47:18Z
3882,2c4341a,Tim Potze,Tim,Potze,None,jdriven,46F9A9BEBD,Jr. Java Developer (JCore),Sourced,False,None,None,True,https://jdriven.workable.com/backend/jobs/3315...,None,None,None,None,2018-08-02T12:15:18Z,2018-08-02T12:19:01Z
3900,2c43a26,Tim Nederlof,Tim,Nederlof,None,jdriven,46F9A9BEBD,Jr. Java Developer (JCore),Sourced,False,None,None,True,https://jdriven.workable.com/backend/jobs/3315...,None,None,None,None,2018-08-02T12:47:22Z,2019-09-11T15:41:35Z
3954,2d8057c,Tim Sijstermans,Tim,Sijstermans,None,jdriven,46F9A9BEBD,Jr. Java Developer (JCore),Talentpool,False,None,None,True,https://jdriven.workable.com/backend/jobs/3315...,None,None,None,None,2018-08-23T13:21:08Z,2019-01-10T12:08:35Z
4104,2ec8131,Tim S,Tim,S,None,jdriven,5E4DC1408A,Data Scientist (Vantage AI),Sourced,False,None,None,True,https://jdriven.workable.com/backend/jobs/6865...,None,None,None,None,2018-09-13T09:44:46Z,2018-09-13T09:44:48Z
4117,2f05859,Tim Faber,Tim,Faber,None,jdriven,5E4DC1408A,Data Scientist (Vantage AI),Sourced,False,None,None,True,https://jdriven.workable.com/backend/jobs/6865...,None,None,None,None,2018-09-17T14:25:35Z,2018-09-21T13:32:03Z
4294,3149e9f,Tim van Wolfswinkel,Tim,van Wolfswinkel,None,jdriven,8176464B66,Front-End Developer (Divotion),Sourced,True,None,None,True,https://jdriven.workable.com/backend/jobs/3403...,None,None,None,None,2018-10-23T13:30:54Z,2019-02-15T10:01:24Z
4395,341a611,Tim Zwart,Tim,Zwart,None,jdriven,46F9A9BEBD,Jr. Java Developer (JCore),Sourced,False,None,None,True,https://jdriven.workable.com/backend/jobs/3315...,None,8414302,None,None,2018-11-12T10:33:12Z,2018-12-10T14:11:35Z
4618,3e7f9c7,Tim Janssen,Tim,Janssen,None,jdriven,EBC47666D5,Corporate Recruiter,Hired,False,None,2019-06-18T12:12:33Z,True,https://jdriven.workable.com/backend/jobs/1013...,None,None,timjanssen393@hotmail.com,None,2019-05-04T19:37:38Z,2019-06-18T12:12:33Z
4645,3ef12a5,Tim De Bruin,Tim,De Bruin,None,jdriven,5E4DC1408A,Data Scientist (Vantage AI),1st Interview,True,None,None,True,https://jdriven.workable.com/backend/jobs/6865...,None,+31628864309,timdebruin89@gmail.com,None,2019-05-10T11:39:48Z,2019-06-03T08:16:24Z
4673,3fb12ea,Tim Bervoets,Tim,Bervoets,Sr Data Scientist,jdriven,A8C5321F60,Big Data Scientist (BDR),Sourced,True,None,None,True,https://jdriven.workable.com/backend/jobs/3292...,"The Hague, South Holland, Netherlands",None,timbervoets@gmail.com,search,2019-05-21T07:55:35Z,2019-05-24T04:22:28Z
4704,4096395,Tim Damen,Tim,Damen,None,jdriven,8176464B66,Front-End Developer (Divotion),Talentpool,False,None,None,True,https://jdriven.workable.com/backend/jobs/3403...,None,0642037461,hello@timdamen.io,None,2019-06-03T11:12:34Z,2019-06-17T16:53:48Z
4755,41d766e,Tim Schuurman,Tim,Schuurman,None,jdriven,5E4DC1408A,Data Scientist (Vantage AI),Review,True,None,None,True,https://jdriven.workable.com/backend/jobs/6865...,None,None,None,None,2019-06-19T13:52:34Z,2019-06-20T16:21:43Z
4798,422cf21,Tim Jansen,Tim,Jansen,None,jdriven,5E4DC1408A,Data Scientist (Vantage AI),Applied,False,None,None,True,https://jdriven.workable.com/backend/jobs/6865...,None,None,None,None,2019-06-25T06:59:22Z,2019-07-02T07:00:33Z
4948,45f02fb,Tim Steinkühler,Tim,Steinkühler,None,jdriven,A8C5321F60,Big Data Scientist (BDR),Applied,False,None,None,True,https://jdriven.workable.com/backend/jobs/3292...,None,None,None,None,2019-08-22T09:47:45Z,2019-08-22T09:49:26Z
4953,45f0306,Tim Janssen,Tim,Janssen,None,jdriven,A8C5321F60,Big Data Scientist (BDR),Applied,False,None,None,True,https://jdriven.workable.com/backend/jobs/3292...,None,None,None,None,2019-08-22T09:47:55Z,2019-09-02T15:41:43Z
5019,472fb24,Tim Van Vliet,Tim,Van Vliet,None,jdriven,46F9A9BEBD,Jr. Java Developer (JCore),Sourced,False,None,None,True,https://jdriven.workable.com/backend/jobs/3315...,None,None,None,None,2019-09-11T09:11:16Z,2019-09-11T09:11:22Z
5024,472fb29,Tim Smeets,Tim,Smeets,None,jdriven,46F9A9BEBD,Jr. Java Developer (JCore),Sourced,False,None,None,True,https://jdriven.workable.com/backend/jobs/3315...,None,+31633814886,timsmeets@rocketmail.com,None,2019-09-11T09:11:16Z,2019-09-11T09:11:27Z

In [22]:
df['name'].value_counts()

Esther Weusthof     4
Top Skills          4
Sander Both         3
Wout Aarts          3
Christiaan Sins     3
                   ..
René Vader          1
Alia Pramadianti    1
Stef Van Gogh       1
Marjolein Vogels    1
Jan-Arie Wolfert    1
Name: name, Length: 4806, dtype: int64

In [31]:
duplicate_names = []
for name in df['name']:
    if df['name'].value_counts()[name]>2:
        duplicate_names.append(name)
duplicate_names

['Tim Janssen',
 'Esther Weusthof',
 'Wout Aarts',
 'Christiaan Sins',
 'Hanrong Zhou',
 'Sander Both',
 'Hanrong Zhou',
 'Hanrong Zhou',
 'Christiaan Sins',
 'Jeroen Zonneveld',
 'Jeroen Zonneveld',
 'Marco Tompitak',
 'Natasa Radenovic',
 'Jeroen Zonneveld',
 'Esther Weusthof',
 'Marco Tompitak',
 'Natasa Radenovic',
 'Natasa Radenovic',
 'Esther Weusthof',
 'Sander Both',
 'Sander Both',
 'Christiaan Sins',
 'Wout Aarts',
 'Wout Aarts',
 'Esther Weusthof',
 'Marco Tompitak',
 'Tim Janssen',
 'Top Skills',
 'Top Skills',
 'Top Skills',
 'Top Skills',
 'Tim Janssen']

In [32]:
df[df['name']=='Natasa Radenovic'].sort_values('created_at')

,id,name,firstname,lastname,headline,subdomain,shortcode,title,stage,disqualified,disqualification_reason,hired_at,sourced,profile_url,address,phone,email,domain,created_at,updated_at
3125,219d4a7,Natasa Radenovic,Natasa,Radenovic,None,jdriven,46F9A9BEBD,Jr. Java Developer (JCore),Talentpool,False,None,None,True,https://jdriven.workable.com/backend/jobs/3315...,None,+31611283280,nradenovic93@gmail.com,None,2018-01-22T09:19:34Z,2019-07-30T04:36:44Z
3325,25cfedd,Natasa Radenovic,Natasa,Radenovic,None,jdriven,46F9A9BEBD,Jr. Java Developer (JCore),Applied,False,None,None,True,https://jdriven.workable.com/backend/jobs/3315...,None,None,None,None,2018-04-10T08:34:08Z,2018-04-10T08:34:11Z
3372,2734b5e,Natasa Radenovic,Natasa,Radenovic,None,jdriven,46F9A9BEBD,Jr. Java Developer (JCore),Applied,True,None,None,True,https://jdriven.workable.com/backend/jobs/3315...,None,None,None,None,2018-05-08T15:07:00Z,2018-05-08T15:44:14Z

In [52]:
d = r_cand.json()['candidates'][0]

In [53]:
d = change_name_duplicate_keys(d)

In [54]:
d

{'id': '470c002',
 'firstname': 'Hasina',
 'lastname': 'Atrafi',
 'headline': None,
 'account': {'subdomain': 'jdriven', 'name': 'JDriven/JCore/BigData Republic'},
 'job': {'shortcode': '08F7250588', 'title': 'Brand Manager'},
 'stage': 'Review',
 'disqualified': False,
 'disqualification_reason': None,
 'hired_at': None,
 'sourced': True,
 'profile_url': 'https://jdriven.workable.com/backend/jobs/1025608/candidates/74496816',
 'address': None,
 'phone': '(0)636108376',
 'email': 'hasina.atrafi@gmail.com',
 'domain': None,
 'created_at': '2019-09-09T13:22:13Z',
 'updated_at': '2019-09-09T14:10:37Z',
 'name_name': 'Hasina Atrafi'}

In [1]:
locate_element()

NameError: name 'locate_element' is not defined

In [12]:
import sqlite3

try:
    connection = sqlite3.connect('example4.db')
    #connection = psycopg2.connect(user = "postgres", password = "maartens1991", host = "127.0.0.1", port = "5432", database = "course_data")
    create_table_q = '''
    CREATE TABLE cand (
    tconst varchar,
    primary key (tconst)
    );'''
    
    cursor = connection.cursor()
    cursor.execute(create_table_q)
    connection.commit()
    
    sql_select_query = '''SELECT column_name
    FROM cand_db.columns
    AND table_name   = 'cand'
    '''
    cursor = connection.cursor()
    cursor.execute(sql_select_query)
    records = cursor.fetchall()
except (Exception, sqlite3.Error) as error :
    print ("Error while connecting to PostgreSQL", error)
finally:
    #Closing database connection.
    if(connection):
        cursor.close()
        connection.close()
        print("PostgreSQL connection is closed")

Error while connecting to PostgreSQL near "AND": syntax error
PostgreSQL connection is closed

In [18]:
    columns = []
    for i in records:
        columns.append(i[0])
    col_n = ','.join(columns)
    
    with open('data.tsv',mode = 'rt', encoding='utf-8') as csv_file, open('data_good.csv', mode='w') as data_good:
        csv_reader = csv.reader(csv_file, delimiter = '\t', quotechar = '|')
        records_to_insert = []
        for row in csv_reader:
            records_to_insert.append(tuple(row))
    records_to_insert_reduced = records_to_insert #[1:1000000]. len(records_to_insert) = 5590840
    params = ['%s' for item in records_to_insert[0]]
    var_string = ','.join(params)
    sql_insert_query = """ INSERT INTO movie_db3 (%s) VALUES (%s);""" %(col_n,var_string)
    cursor = connection.cursor()
    cursor.executemany(sql_insert_query, records_to_insert_reduced)
    connection.commit()

NameError: name 'records' is not defined

In [19]:
import sqlite3
conn = sqlite3.connect('candidate_schema.db')
c = conn.cursor()

# Create table
c.execute('''CREATE TABLE stocks
             (date text, trans text, symbol text, qty real, price real)''')

# Insert a row of data
c.execute("INSERT INTO stocks VALUES ('2006-01-05','BUY','RHAT',100,35.14)")

# Save (commit) the changes
conn.commit()

# We can also close the connection if we are done with it.
# Just be sure any changes have been committed or they will be lost.
conn.close()

OperationalError: table stocks already exists

In [20]:
import MySQLdb

import sqlite3
conn = sqlite3.connect('candidate_schema.db')
c = conn.cursor()

# Create table
c.execute('''CREATE TABLE stocks
             (date text, trans text, symbol text, qty real, price real)''')

# Insert a row of data
c.execute("INSERT INTO stocks VALUES ('2006-01-05','BUY','RHAT',100,35.14)")

# Save (commit) the changes
conn.commit()

# We can also close the connection if we are done with it.
# Just be sure any changes have been committed or they will be lost.
conn.close()

ModuleNotFoundError: No module named 'MySQLdb'

In [5]:
import mysql.connector
conn = mysql.connector.connect(user='root', password='maartens1991',host='localhost', database='recruitment_dashboard')
c = conn.cursor()

# Create table
c.execute('''CREATE TABLE candidates
             (date text, trans text, symbol text, qty real, price real)''')

# Insert a row of data
c.execute("INSERT INTO stocks VALUES ('2006-01-05','BUY','RHAT',100,35.14)")

# Save (commit) the changes
conn.commit()

# We can also close the connection if we are done with it.
# Just be sure any changes have been committed or they will be lost.
conn.close()

In [ ]:
try:
    connection = mysql.connector.connect(user='root', password='maartens1991',host='localhost', database='recruitment_dashboard')
    create_table_q = '''
    CREATE TABLE candidates (
    tconst varchar,
    titleType varchar,
    primaryTitle varchar,
    originalTitle varchar,
    isAdult varchar,
    startYear varchar,
    endYear varchar,
    runtimeMinutes varchar,
    genres varchar,
    primary key (tconst)
    );'''
    
    cursor = connection.cursor()
    cursor.execute(create_table_q)
    connection.commit()
    
    sql_select_query = '''SELECT column_name
    FROM information_schema.columns
    WHERE table_schema = 'public'
    AND table_name   = 'candidates'
    '''
    cursor = connection.cursor()
    cursor.execute(sql_select_query)
    records = cursor.fetchall()
    columns = []
    for i in records:
        columns.append(i[0])
    col_n = ','.join(columns)
    
    with open('data.tsv',mode = 'rt', encoding='utf-8') as csv_file, open('data_good.csv', mode='w') as data_good:
        csv_reader = csv.reader(csv_file, delimiter = '\t', quotechar = '|')
        records_to_insert = []
        for row in csv_reader:
            records_to_insert.append(tuple(row))
    records_to_insert_reduced = records_to_insert #[1:1000000]. len(records_to_insert) = 5590840
    params = ['%s' for item in records_to_insert[0]]
    var_string = ','.join(params)
    sql_insert_query = """ INSERT INTO movie_db3 (%s) VALUES (%s);""" %(col_n,var_string)
    cursor = connection.cursor()
    cursor.executemany(sql_insert_query, records_to_insert_reduced)
    connection.commit()
except (Exception, psycopg2.Error) as error :
    print ("Error while connecting to PostgreSQL", error)
finally:
    #Closing database connection.
    if(connection):
        cursor.close()
        connection.close()
        print("PostgreSQL connection is closed")